# # 1
# fruits = ['olma', 'banan', 'uzum']
# fruits.append('nok')
# print(fruits)
# print(len(fruits))
# print("olma" in fruits)
# print(fruits.index("banan"))
# # 2
# colors = ["qizil", "yashil", "ko'k"]
# colors.append("sariq")
# print(colors)
# colors.sort()
# print(colors)
# print(len(colors))
# print("yashil" in colors)
# # 3
# cities = ['Toshkent', 'Samarqand', 'Buxoro']
# cities.append('Xiva')
# print(cities)
# print(cities.index('Samarqand'))
# print(len(cities))
# cities.sort()
# print(cities)
# # 4
# numbers = [5, 2, 8, 1]
# numbers.append(10)
# print(numbers)
# numbers.sort()
# print(numbers)
# print(len(numbers))
# print(8 in numbers)
# # 5
# animals = ['mushuk', 'it', 'qush']
# animals.append('baliq')
# print(animals)
# animals.sort()
# print(animals)
# print(animals.index('it'))
# print(len(animals))
# # 6
# fruits = ['olma', 'banan', 'uzum', 'nok']
# fruits.append("kivi")
# print(fruits)
# fruits.remove("banan")
# print(fruits)
# fruits.insert(-2, "shaftoli" )
# print(fruits)
# fruits.sort()
# print(fruits)
# print(len(fruits))
# print(fruits.index("olma"))
# print("kivi" in fruits)
# fruits.sort(reverse=True)
# print(fruits)
# fruits2 = fruits.copy()
# fruits2.append("ananas")
# print(fruits)
# print(fruits2)
# # 7
# menu = ['osh', "lag'mon", 'shashlik', 'somsa']
# menu.extend(["manti" , "norin"])
# print(menu)
# menu.remove("lag'mon")
# print(menu)
# menu.pop()
# print(menu)
# print(len(menu))
# print(menu.index("osh"))
# print(menu.count("somsa"))
# print("manti" in menu)
# meni1 = menu.copy()
# meni1.append("qozon kabob")
# print(menu)
# print(meni1)
# # 8
# cities = ['Toshkent', 'Samarqand', 'Buxoro', 'Xiva']
# cities.insert(0, 'Andijon')
# print(cities)
# cities.remove('Xiva')
# print(cities)
# print(cities.index('Samarqand'))
# cities.sort()
# print(cities)
# print(len(cities))
# print("Buxoro" in cities)
# cities.pop()
# print(cities)
# cities.sort(reverse=True)
# print(cities)
# cities1 = cities.copy()
# cities1.append("Farg'ona")
# print(cities)
# print(cities1)
# # 9
# students = ['Ali', 'Vali', 'Sardor', 'Aziz']
# students.append("Jamshid")
# print(students)
# students.remove("Sardor")
# print(students)
# students.sort()
# print(students)
# print(students.index("Aziz"))
# print("Diyor" in students)
# students.pop()
# print(len(students))
# students1 = students.copy()
# students1.append("Nodir")
# print(students)
# print(students1)
# # 10
# favorites = ['telefon', 'noutbuk', 'naushnik']
# favorites.append("planshet")
# print(favorites)
# favorites.append("soat")
# print(favorites)
# favorites.sort()
# print(favorites)
# print(len(favorites))
# print(favorites.index('naushnik'))
# print("telefon" in favorites)
# favorites.remove('naushnik')
# print(favorites)
# favorites.pop()
# print(favorites)
# favorites2 = favorites.copy()
# favorites2.append("televizor")
# favorites2.sort(reverse=True)
# print(favorites)
# print(favorites2)
# # 11
# songs = ["Yomg'ir", 'Sevgi', 'Hayot', 'Kuz']
# songs.insert(1 , "Baxor")
# print(songs)
# songs.remove("Kuz")
# print(songs)
# songs.sort()
# print(songs)
# print(songs.index("Yomg'ir"))
# print("Hayot" in songs)
# songs.pop()
# print(songs)
# print(len(songs))
# songs.sort(reverse=True)
# print(songs)
# songs1 = songs.copy()
# songs1.append("Yoz")
# print(songs)
# print(songs1)
# # 12
# books = ['Alximik', 'Shaytanat', '1984']
# books.extend(["O'tkan kunlar", 'Sariq devni minib'])
# print(books)
# books.remove('Shaytanat')
# print(books)
# books.sort()
# print(books)
# print(books.index('1984'))
# print("Alximik" in books)
# books.pop()
# print(books)
# print(len(books))
# books.sort(reverse=True)
# print(books)
# books1 = books.copy()
# books1.append("Qirq yil")
# print(books)
# print(books1)
# # 13
# movies = ['Inception', 'Matrix', 'Interstellar']
# movies.append('Parasite')
# print(movies)
# movies.remove('Matrix')
# print(movies)
# movies.sort()
# print(movies)
# print(movies.index("Inception"))
# print("International" in movies)
# movies.pop()
# print(movies)
# print(len(movies))
# movies.sort(reverse=True)
# print(movies)
# movies1 = movies.copy()
# movies1.append("Joker")
# print(movies)
# print(movies1)
# # 14
# emails = ['job_offer', 'spam', 'friend', 'news']
# emails.append('family')
# print(emails)
# emails.remove('spam')
# print(emails)
# emails.sort()
# print(emails)
# print(emails.index('friend'))
# print("job_offer" in emails)
# emails.pop()
# print(emails)
# print(len(emails))
# emails.sort(reverse=True)
# print(emails)
# emails1 = emails.copy()
# emails1.append('urgent')
# print(emails)
# print(emails1)
# # 15
# friends = ['Ali', 'Zara', 'Bobur', 'Nodir']
# friends.append('Jamol')
# print(friends)
# friends.remove('Nodir')
# print(friends)
# friends.sort()
# print(friends)
# print("Ali" in friends)
# friends.pop()
# print(friends)
# print(len(friends))
# friends.sort(reverse=True)
# print(friends)
# friends1 = friends.copy()
# friends1.append('Sardor')
# print(friends)
# print(friends1)
# # 16
# animals = ['sher', 'yo\'lbars', 'ayiq', 'sher', 'quyon']
# print(animals.count('sher'))
# animals.remove("ayiq")
# print(animals)
# animals.append("kenguru")
# print(animals)
# animals.sort()
# print(animals)
# print(animals.index('yo\'lbars'))
# print("quyon" in animals)
# animals.pop()
# print(animals)
# print(len(animals))
# animals1 = animals.copy()
# animals1.append("tuya")
# print(animals)
# print(animals1)
# # 17
# champions = ['Khamzat Chimaev', 'Khabib Nurmagomedov', 'Conor McGregor', 'Mike Tyson', 'Wladimir Klichko', 'Eliud']
# print(champions.count("Mike Tyson"))
# champions.pop()
# champions.extend("Bahodir Jalolov" , "Hasanboy Do'smatov")
# print(champions)
# champions.sort()
# print(champions.index('Mike Tyson'))
# print("Khabib Nurmagomedov" in champions)
# champions.remove('Conor McGregor')
# print(champions)
# print(len(champions))
# champions1 = champions.copy()
# champions1.append('Shaxram G\'iyasov')
# print(champions)
# print(champions1)
# # 18
# cart = ['non', 'suyut', 'tuxum', "go'sht"]
# print(cart.index("tuxum"))
# cart.remove("suyut")
# print(cart)
# cart.extend(['sari yog\'' , 'murabbo'])
# print(cart)
# cart.sort()
# print(cart)
# cart1 = cart.copy()
# cart1.append("shakar")
# print(cart)
# print(cart1)
# cart.clear()
# print(cart)
# print("non" in cart)
# print(len(cart))
# cart1 = cart.copy()
# cart1.pop()
# print(cart)
# print(cart1)
# # 19
# courses = ['Python', 'Java', 'Data Science', 'Python']
# courses.count('Python')
# print(courses)
# courses.remove('Java')
# print(courses)
# courses.extend('Al' , 'Web Development')
# print(courses)
# courses.sort()
# print(courses)
# print(courses.index('Data Science'))
# print('Al' in courses)
# courses.pop()
# print(courses)
# courses.remove('Python')
# print(courses)
# print(len(courses))
# courses1 = courses.copy()
# courses1.append('Blockchain')
# print(courses)
# print(courses1)
# # 20
# cars = ['Chevrolet', 'Hyundai', 'Kia', 'Toyota']
# cars.insert(0, 'BMW')
# print(cars)
# cars.remove('Kia')
# print(cars)
# cars1 = cars.copy()
# print(cars1)
# cars.sort()
# print(cars)
# print(cars.index('Toyota'))
# print("Hyundai" in cars)
# cars.pop()
# print(cars)
# print(len(cars))
# cars.sort(reverse=True)
# print(cars)
# cars.clear()
# cars1.append('Mercedes')
# print(cars)
# print(cars1)













